Repository nuke-build/nuke, pull requests merged in 2023-02, with the labels that each got.

#994 Add reminder to clear clipboard after secret was added
  source/Nuke.GlobalTool/Program.Secrets.cs
Labels: area:core

#1065 Update Azure Pipelines Publish step
  source/Nuke.Common.Tests/CI/ConfigurationGenerationTest.Test_testName=null_attribute=AzurePipelinesAttribute.verified.txt
  source/Nuke.Common/CI/AzurePipelines/AzurePipelinesAttribute.cs
  source/Nuke.Common/CI/AzurePipelines/Configuration/AzurePipelinesPublishStep.cs
Labels: area:cicd

#853 Added missing type name parameters for Kubernetes create and delete
  source/Nuke.Common/Tools/Kubernetes/Kubernetes.json
Labels: area:tools
